name: Deploy to Linode

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Create .env file
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "NODE_ENV=production" >> .env
        echo "DB_PATH=${{ secrets.DB_PATH }}" >> .env
        # Add any other environment variables here

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy to Linode
      run: |
        # Create deployment package
        tar -czf deploy.tar.gz dist/ public/ package.json package-lock.json .env data/ scripts/ ecosystem.config.js

        # Copy files to server
        scp deploy.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app/

        # Execute deployment script on server
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ~/app && tar -xzf deploy.tar.gz && npm ci --production && pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js'
